services:
  mysql:
    image: mysql:8.0
    container_name: hotlse-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hotlse
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

volumes:
  dbdata:
    driver: local

